# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'constantwatering.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_constantwateringWindow(object):
    def setupUi(self, constantwateringWindow):
        constantwateringWindow.setObjectName("constantwateringWindow")
        constantwateringWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(constantwateringWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 281, 41))
        self.label.setStyleSheet("font: 16pt \"Corbel\";")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 140, 491, 51))
        self.pushButton.setStyleSheet("font: 75 13pt \"Corbel\";\n"
"background-color: rgb(49, 124, 9);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 360, 41, 41))
        self.pushButton_2.setStyleSheet("font: 15pt \"Corbel\";\n"
"\n"
"background-color: rgb(49, 124, 9);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 190, 841, 161))
        self.label_2.setStyleSheet("font: 25 14pt \"Corbel Light\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 80, 381, 31))
        self.label_3.setStyleSheet("font: 16pt \"Corbel\";")
        self.label_3.setObjectName("label_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(100, 360, 41, 41))
        self.pushButton_3.setStyleSheet("font: 15pt \"Corbel\";\n"
"\n"
"background-color: rgb(49, 124, 9);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(170, 360, 41, 41))
        self.pushButton_4.setStyleSheet("font: 15pt \"Corbel\";\n"
"\n"
"background-color: rgb(49, 124, 9);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(310, 360, 41, 41))
        self.pushButton_5.setStyleSheet("font: 15pt \"Corbel\";\n"
"\n"
"background-color: rgb(49, 124, 9);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(240, 360, 41, 41))
        self.pushButton_6.setStyleSheet("font: 15pt \"Corbel\";\n"
"\n"
"background-color: rgb(49, 124, 9);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(170, 430, 41, 41))
        self.pushButton_7.setStyleSheet("font: 15pt \"Corbel\";\n"
"\n"
"background-color: rgb(49, 124, 9);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(100, 430, 41, 41))
        self.pushButton_8.setStyleSheet("font: 15pt \"Corbel\";\n"
"\n"
"background-color: rgb(49, 124, 9);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(240, 430, 41, 41))
        self.pushButton_9.setStyleSheet("font: 15pt \"Corbel\";\n"
"\n"
"background-color: rgb(49, 124, 9);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(30, 430, 41, 41))
        self.pushButton_10.setStyleSheet("font: 15pt \"Corbel\";\n"
"\n"
"background-color: rgb(49, 124, 9);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(310, 430, 41, 41))
        self.pushButton_11.setStyleSheet("font: 15pt \"Corbel\";\n"
"\n"
"background-color: rgb(49, 124, 9);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_11.setObjectName("pushButton_11")
        constantwateringWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(constantwateringWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 880, 21))
        self.menubar.setObjectName("menubar")
        constantwateringWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(constantwateringWindow)
        self.statusbar.setObjectName("statusbar")
        constantwateringWindow.setStatusBar(self.statusbar)

        self.retranslateUi(constantwateringWindow)
        QtCore.QMetaObject.connectSlotsByName(constantwateringWindow)

    def retranslateUi(self, constantwateringWindow):
        _translate = QtCore.QCoreApplication.translate
        constantwateringWindow.setWindowTitle(_translate("constantwateringWindow", "Constant Watering"))
        self.label.setText(_translate("constantwateringWindow", "Constant watering"))
        self.pushButton.setText(_translate("constantwateringWindow", "KEEP THE CURRENT MOISTURE LEVEL"))
        self.pushButton_2.setText(_translate("constantwateringWindow", "1"))
        self.label_2.setText(_translate("constantwateringWindow", "This option will save the current soil moisture level\n and keep the soil moist "
"at the level.\n"
"\n"
"Or choose a moisture level from below."))
        self.label_3.setText(_translate("constantwateringWindow", "CHOOSE YOUR OPTION"))
        self.pushButton_3.setText(_translate("constantwateringWindow", "2"))
        self.pushButton_4.setText(_translate("constantwateringWindow", "3"))
        self.pushButton_5.setText(_translate("constantwateringWindow", "5"))
        self.pushButton_6.setText(_translate("constantwateringWindow", "4"))
        self.pushButton_7.setText(_translate("constantwateringWindow", "8"))
        self.pushButton_8.setText(_translate("constantwateringWindow", "7"))
        self.pushButton_9.setText(_translate("constantwateringWindow", "9"))
        self.pushButton_10.setText(_translate("constantwateringWindow", "6"))
        self.pushButton_11.setText(_translate("constantwateringWindow", "10"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    constantwateringWindow = QtWidgets.QMainWindow()
    ui = Ui_constantwateringWindow()
    ui.setupUi(constantwateringWindow)
    constantwateringWindow.show()
    sys.exit(app.exec_())
