# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newplant.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from scheduledwatering import Ui_scheduledwateringWindow
from constantwatering import Ui_constantwateringWindow

class Ui_NewplantWindow(object):
    def openscheduledwateringWindow(self) :
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_scheduledwateringWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        NewplantWindow.hide()
    def openconstantwateringWindow(self) :
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_constantwateringWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        NewplantWindow.hide()

    def setupUi(self, NewplantWindow):
        NewplantWindow.setObjectName("NewplantWindow")
        NewplantWindow.setEnabled(True)
        NewplantWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(NewplantWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.nameyourplantlabel = QtWidgets.QLabel(self.centralwidget)
        self.nameyourplantlabel.setGeometry(QtCore.QRect(50, 30, 211, 31))
        self.nameyourplantlabel.setStyleSheet("font: 14pt \"Calibri\";")
        self.nameyourplantlabel.setObjectName("nameyourplantlabel")
        self.chooseplanlabel = QtWidgets.QLabel(self.centralwidget)
        self.chooseplanlabel.setGeometry(QtCore.QRect(50, 110, 421, 51))
        self.chooseplanlabel.setStyleSheet("font: 14pt \"Calibri\";")
        self.chooseplanlabel.setObjectName("chooseplanlabel")
        self.constantwateringpushButton = QtWidgets.QPushButton(self.centralwidget)
        self.constantwateringpushButton.setGeometry(QtCore.QRect(50, 170, 301, 31))
        self.constantwateringpushButton.setStyleSheet("font: 75 13pt \"Corbel\";\n"
"background-color: rgb(49, 124, 9);\n"
"color: rgb(255, 255, 255);")
        self.constantwateringpushButton.setObjectName("constantwateringpushButton")
        self.constantwateringpushButton.clicked.connect(self.openconstantwateringWindow)


        self.scheduledwateringpushButton = QtWidgets.QPushButton(self.centralwidget)
        self.scheduledwateringpushButton.setGeometry(QtCore.QRect(50, 320, 301, 31))
        self.scheduledwateringpushButton.setStyleSheet("font: 75 13pt \"Corbel\";\n"
"background-color: rgb(49, 124, 9);\n"
"color: rgb(255, 255, 255);")
        self.scheduledwateringpushButton.setObjectName("scheduledwateringpushButton")
        self.scheduledwateringpushButton.clicked.connect(self.openscheduledwateringWindow)


        self.constanttextlabel = QtWidgets.QLabel(self.centralwidget)
        self.constanttextlabel.setGeometry(QtCore.QRect(50, 200, 741, 111))
        self.constanttextlabel.setStyleSheet("\n"
"font: 12pt \"Corbel\";")
        self.constanttextlabel.setObjectName("constanttextlabel")
        self.scheduledtextlabel = QtWidgets.QLabel(self.centralwidget)
        self.scheduledtextlabel.setGeometry(QtCore.QRect(50, 350, 781, 91))
        self.scheduledtextlabel.setStyleSheet("\n"
"font: 12pt \"Corbel\";")
        self.scheduledtextlabel.setObjectName("scheduledtextlabel")
        self.plantnamelineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.plantnamelineEdit.setGeometry(QtCore.QRect(260, 30, 231, 31))
        self.plantnamelineEdit.setObjectName("plantnamelineEdit")
        NewplantWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(NewplantWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        NewplantWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(NewplantWindow)
        self.statusbar.setObjectName("statusbar")
        NewplantWindow.setStatusBar(self.statusbar)

        self.retranslateUi(NewplantWindow)
        QtCore.QMetaObject.connectSlotsByName(NewplantWindow)

    def retranslateUi(self, NewplantWindow):
        _translate = QtCore.QCoreApplication.translate
        NewplantWindow.setWindowTitle(_translate("NewplantWindow", "New plant"))
        self.nameyourplantlabel.setText(_translate("NewplantWindow", "Name your plant: "))
        self.chooseplanlabel.setText(_translate("NewplantWindow", "Choose watering plan for your plant"))
        self.constantwateringpushButton.setText(_translate("NewplantWindow", "CONSTANT WATERING"))
        self.scheduledwateringpushButton.setText(_translate("NewplantWindow", "SCHEDULED WATERING"))
        self.constanttextlabel.setText(_translate("NewplantWindow", "Constant watering will always keep the soil at a certain moisture level of \n"
"the user\'s choice as long as the water tank is not empty. "))
        self.scheduledtextlabel.setText(_translate("NewplantWindow", "\n"
"Scheduled watering will water your plant at a certain time with a certain \n"
"amount of water."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewplantWindow = QtWidgets.QMainWindow()
    ui = Ui_NewplantWindow()
    ui.setupUi(NewplantWindow)
    NewplantWindow.show()
    sys.exit(app.exec_())
