# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'playingg.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1.setGeometry(QtCore.QRect(20, 110, 731, 71))
        self.pushButton1.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(80, 168, 78);\n"
"font: 75 14pt \"Corbel\";")
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton1_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1_2.setGeometry(QtCore.QRect(20, 190, 731, 71))
        self.pushButton1_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(80, 168, 78);\n"
"font: 75 14pt \"Corbel\";")
        self.pushButton1_2.setObjectName("pushButton1_2")
        self.connectionlabel = QtWidgets.QLabel(self.centralwidget)
        self.connectionlabel.setGeometry(QtCore.QRect(20, 20, 201, 71))
        self.connectionlabel.setStyleSheet("background-color: rgb(19, 132, 72);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Corbel\";")
        self.connectionlabel.setObjectName("connectionlabel")
        self.developedbylabel = QtWidgets.QLabel(self.centralwidget)
        self.developedbylabel.setGeometry(QtCore.QRect(520, 20, 231, 71))
        self.developedbylabel.setStyleSheet("font: italic 9pt \"Arial\";")
        self.developedbylabel.setObjectName("developedbylabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 867, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Plants near me"))
        self.pushButton1.setText(_translate("MainWindow", "Registered plant 1"))
        self.pushButton1_2.setText(_translate("MainWindow", "New plant"))
        self.connectionlabel.setText(_translate("MainWindow", "     Connected"))
        self.developedbylabel.setText(_translate("MainWindow", "Developed by Protodudes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
