# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'planthome.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_planthomeWindow(object):
    def setupUi(self, planthomeWindow):
        planthomeWindow.setObjectName("planthomeWindow")
        planthomeWindow.resize(728, 504)
        self.centralwidget = QtWidgets.QWidget(planthomeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plantnamelabel1 = QtWidgets.QLabel(self.centralwidget)
        self.plantnamelabel1.setGeometry(QtCore.QRect(30, 20, 131, 21))
        self.plantnamelabel1.setStyleSheet("font: 14pt \"Calibri\";")
        self.plantnamelabel1.setObjectName("plantnamelabel1")
        self.plantnamelabel2 = QtWidgets.QLabel(self.centralwidget)
        self.plantnamelabel2.setGeometry(QtCore.QRect(160, 20, 151, 21))
        self.plantnamelabel2.setStyleSheet("font: 14pt \"Calibri\";")
        self.plantnamelabel2.setObjectName("plantnamelabel2")
        self.moisturelevellabel1 = QtWidgets.QLabel(self.centralwidget)
        self.moisturelevellabel1.setGeometry(QtCore.QRect(40, 100, 311, 31))
        self.moisturelevellabel1.setStyleSheet("font: 75 14pt \"Calibri\";")
        self.moisturelevellabel1.setObjectName("moisturelevellabel1")
        self.currentsettingslabel = QtWidgets.QLabel(self.centralwidget)
        self.currentsettingslabel.setGeometry(QtCore.QRect(40, 60, 231, 31))
        self.currentsettingslabel.setStyleSheet("font: 14pt \"Calibri\";")
        self.currentsettingslabel.setObjectName("currentsettingslabel")
        self.mositurelevellabel2 = QtWidgets.QLabel(self.centralwidget)
        self.mositurelevellabel2.setGeometry(QtCore.QRect(350, 100, 161, 31))
        self.mositurelevellabel2.setStyleSheet("font: 75 14pt \"Calibri\";")
        self.mositurelevellabel2.setObjectName("mositurelevellabel2")
        self.wateringplan1 = QtWidgets.QLabel(self.centralwidget)
        self.wateringplan1.setGeometry(QtCore.QRect(40, 150, 261, 31))
        self.wateringplan1.setStyleSheet("font: 75 14pt \"Calibri\";")
        self.wateringplan1.setObjectName("wateringplan1")
        self.wateringplan2 = QtWidgets.QLabel(self.centralwidget)
        self.wateringplan2.setGeometry(QtCore.QRect(40, 190, 261, 31))
        self.wateringplan2.setStyleSheet("font: 75 14pt \"Calibri\";")
        self.wateringplan2.setObjectName("wateringplan2")
        self.wateringplan3 = QtWidgets.QLabel(self.centralwidget)
        self.wateringplan3.setGeometry(QtCore.QRect(40, 230, 291, 31))
        self.wateringplan3.setStyleSheet("font: 75 14pt \"Calibri\";")
        self.wateringplan3.setObjectName("wateringplan3")
        self.changebutton = QtWidgets.QPushButton(self.centralwidget)
        self.changebutton.setGeometry(QtCore.QRect(30, 280, 421, 41))
        self.changebutton.setStyleSheet("font: 13.5pt \"Calibri\";\n"
"background-color: rgb(195, 225, 182);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"")
        self.changebutton.setObjectName("changebutton")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(30, 350, 611, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.homebutton = QtWidgets.QPushButton(self.centralwidget)
        self.homebutton.setGeometry(QtCore.QRect(590, 30, 71, 71))
        self.homebutton.setStyleSheet("background-color: rgb(216, 255, 211);")
        self.homebutton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/ico_breadcrumb_home_off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homebutton.setIcon(icon)
        self.homebutton.setIconSize(QtCore.QSize(50, 50))
        self.homebutton.setObjectName("homebutton")
        planthomeWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(planthomeWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 728, 21))
        self.menubar.setObjectName("menubar")
        self.menuFirst_tab = QtWidgets.QMenu(self.menubar)
        self.menuFirst_tab.setObjectName("menuFirst_tab")
        planthomeWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(planthomeWindow)
        self.statusbar.setObjectName("statusbar")
        planthomeWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFirst_tab.menuAction())

        self.retranslateUi(planthomeWindow)
        QtCore.QMetaObject.connectSlotsByName(planthomeWindow)

    def retranslateUi(self, planthomeWindow):
        _translate = QtCore.QCoreApplication.translate
        planthomeWindow.setWindowTitle(_translate("planthomeWindow", "Plant1 Page"))
        self.plantnamelabel1.setText(_translate("planthomeWindow", "Plant Name:"))
        self.plantnamelabel2.setText(_translate("planthomeWindow", "Plant1"))
        self.moisturelevellabel1.setText(_translate("planthomeWindow", "Current Soil Moisture level:"))
        self.currentsettingslabel.setText(_translate("planthomeWindow", "Current Settings"))
        self.mositurelevellabel2.setText(_translate("planthomeWindow", "7/10"))
        self.wateringplan1.setText(_translate("planthomeWindow", "Current Watering Plan:"))
        self.wateringplan2.setText(_translate("planthomeWindow", "Scheduled watering"))
        self.wateringplan3.setText(_translate("planthomeWindow", "Every 7 day(s), 200 ml"))
        self.changebutton.setText(_translate("planthomeWindow", "Change the watering plan"))
        self.menuFirst_tab.setTitle(_translate("planthomeWindow", "Home"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    planthomeWindow = QtWidgets.QMainWindow()
    ui = Ui_planthomeWindow()
    ui.setupUi(planthomeWindow)
    planthomeWindow.show()
    sys.exit(app.exec_())
