# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scheduledwatering.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from plantsnearme import Ui_MainWindow

class Ui_scheduledwateringWindow(object):
    def openWindow(self) :
        old = self.window
        print(old)
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, scheduledwateringWindow):
        scheduledwateringWindow.setObjectName("scheduledwateringWindow")
        scheduledwateringWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(scheduledwateringWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scheduledtoplabel = QtWidgets.QLabel(self.centralwidget)
        self.scheduledtoplabel.setGeometry(QtCore.QRect(30, 20, 281, 31))
        self.scheduledtoplabel.setStyleSheet("font: 16pt \"Corbel\";")
        self.scheduledtoplabel.setObjectName("scheduledtoplabel")
        self.Schooseoptionlabel = QtWidgets.QLabel(self.centralwidget)
        self.Schooseoptionlabel.setGeometry(QtCore.QRect(30, 70, 361, 31))
        self.Schooseoptionlabel.setStyleSheet("font: 16pt \"Corbel\";")
        self.Schooseoptionlabel.setObjectName("Schooseoptionlabel")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(130, 150, 61, 31))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.howoftenlabel = QtWidgets.QLabel(self.centralwidget)
        self.howoftenlabel.setGeometry(QtCore.QRect(30, 110, 501, 31))
        self.howoftenlabel.setStyleSheet("\n"
"font: 25 14pt \"Corbel Light\";")
        self.howoftenlabel.setObjectName("howoftenlabel")
        self.Severy1label = QtWidgets.QLabel(self.centralwidget)
        self.Severy1label.setGeometry(QtCore.QRect(40, 150, 81, 31))
        self.Severy1label.setStyleSheet("\n"
"font: 25 14pt \"Corbel Light\";")
        self.Severy1label.setObjectName("Severy1label")
        self.hourslabel = QtWidgets.QLabel(self.centralwidget)
        self.hourslabel.setGeometry(QtCore.QRect(200, 150, 101, 31))
        self.hourslabel.setStyleSheet("\n"
"font: 25 14pt \"Corbel Light\";")
        self.hourslabel.setObjectName("hourslabel")
        self.numofdayslabel = QtWidgets.QLabel(self.centralwidget)
        self.numofdayslabel.setGeometry(QtCore.QRect(30, 190, 351, 31))
        self.numofdayslabel.setStyleSheet("\n"
"font: 25 14pt \"Corbel Light\";")
        self.numofdayslabel.setObjectName("numofdayslabel")
        self.wateramountlabel = QtWidgets.QLabel(self.centralwidget)
        self.wateramountlabel.setGeometry(QtCore.QRect(30, 290, 571, 31))
        self.wateramountlabel.setStyleSheet("\n"
"font: 25 14pt \"Corbel Light\";")
        self.wateramountlabel.setObjectName("wateramountlabel")
        self.wateramountplainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.wateramountplainTextEdit.setGeometry(QtCore.QRect(40, 330, 61, 31))
        self.wateramountplainTextEdit.setObjectName("wateramountplainTextEdit")
        self.mllabel = QtWidgets.QLabel(self.centralwidget)
        self.mllabel.setGeometry(QtCore.QRect(110, 330, 81, 31))
        self.mllabel.setStyleSheet("\n"
"font: 25 14pt \"Corbel Light\";")
        self.mllabel.setObjectName("mllabel")
        self.savepushButton = QtWidgets.QPushButton(self.centralwidget)
        self.savepushButton.setGeometry(QtCore.QRect(50, 412, 131, 31))
        self.savepushButton.setStyleSheet("font: 75 13pt \"Corbel\";\n"
"background-color: rgb(49, 124, 9);\n"
"color: rgb(255, 255, 255);")
        self.savepushButton.setObjectName("savepushButton")
        self.savepushButton.clicked.connect(self.openWindow)


        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(130, 230, 61, 31))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.Severy2label = QtWidgets.QLabel(self.centralwidget)
        self.Severy2label.setGeometry(QtCore.QRect(40, 230, 81, 31))
        self.Severy2label.setStyleSheet("\n"
"font: 25 14pt \"Corbel Light\";")
        self.Severy2label.setObjectName("Severy2label")
        self.dayslabel = QtWidgets.QLabel(self.centralwidget)
        self.dayslabel.setGeometry(QtCore.QRect(200, 230, 101, 31))
        self.dayslabel.setStyleSheet("\n"
"font: 25 14pt \"Corbel Light\";")
        self.dayslabel.setObjectName("dayslabel")
        scheduledwateringWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(scheduledwateringWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        scheduledwateringWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(scheduledwateringWindow)
        self.statusbar.setObjectName("statusbar")
        scheduledwateringWindow.setStatusBar(self.statusbar)

        self.retranslateUi(scheduledwateringWindow)
        QtCore.QMetaObject.connectSlotsByName(scheduledwateringWindow)

    def retranslateUi(self, scheduledwateringWindow):
        _translate = QtCore.QCoreApplication.translate
        scheduledwateringWindow.setWindowTitle(_translate("scheduledwateringWindow", "Scheduled Watering"))
        self.scheduledtoplabel.setText(_translate("scheduledwateringWindow", "Scheduled Watering"))
        self.Schooseoptionlabel.setText(_translate("scheduledwateringWindow", "CHOOSE YOUR OPTION"))
        self.howoftenlabel.setText(_translate("scheduledwateringWindow", "How often do you want your plant watered?"))
        self.Severy1label.setText(_translate("scheduledwateringWindow", "Every"))
        self.hourslabel.setText(_translate("scheduledwateringWindow", "hour(s)"))
        self.numofdayslabel.setText(_translate("scheduledwateringWindow", "Or choose the number of days"))
        self.wateramountlabel.setText(_translate("scheduledwateringWindow", "And choose the amount of water"))
        self.mllabel.setText(_translate("scheduledwateringWindow", "ml"))
        self.savepushButton.setText(_translate("scheduledwateringWindow", "Save"))
        self.Severy2label.setText(_translate("scheduledwateringWindow", "Every"))
        self.dayslabel.setText(_translate("scheduledwateringWindow", "day(s)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    scheduledwateringWindow = QtWidgets.QMainWindow()
    ui = Ui_scheduledwateringWindow()
    ui.setupUi(scheduledwateringWindow)
    scheduledwateringWindow.show()
    sys.exit(app.exec_())
